const SourceFirst = <String, List<String>>{
  "<Logical Denied>": ["!"],
  "<Index>": ["DecLiteral"],
  "<Function Call>": ["Identifier"],
  "<Value_assigned_matrix>": [
    "OctLiteral",
    "DecLiteral",
    "HexLiteral",
    "FloatLiteral",
    "StringLiteral",
    "true",
    "false"
  ],
  "<Number>": ["FloatLiteral", "OctLiteral", "DecLiteral", "HexLiteral"],
  "<Logical Expression>": [
    "local.",
    "!",
    "FloatLiteral",
    "-",
    "false",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "HexLiteral",
    "true"
  ],
  "<Global Decl>": ["const", "", "var"],
  "<Else Procedure>": ["else", ""],
  "<Term>": [
    "true",
    "HexLiteral",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "FloatLiteral",
    "(",
    "StringLiteral",
    "false",
    "-"
  ],
  "<Type>": ["int", "boolean", "real", "Identifier", "struct", "string"],
  "<Typedef Decl>": ["typedef"],
  "<Relational>": ["<", ">", ">=", "!=", "==", "<="],
  "<Function Declaration>": ["function"],
  "<Body Item Procedure>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "Identifier",
    "if",
    "DecLiteral",
    "false",
    "(",
    "HexLiteral",
    "FloatLiteral",
    "OctLiteral"
  ],
  "<Relational Expression>": [
    "local.",
    "FloatLiteral",
    "-",
    "HexLiteral",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<If>": ["if"],
  "<Else>": ["else", ""],
  "<ConstList>": [
    "Identifier",
    "boolean",
    "",
    "real",
    "string",
    "struct",
    "int"
  ],
  "<Struct Decl>": ["struct"],
  "<Assignment_vector_aux2>": ["="],
  "<Extends>": ["", "extends"],
  "<PrefixGlobalLocal>": ["global.", "local."],
  "<Read>": ["read"],
  "<Value>": [
    "OctLiteral",
    "DecLiteral",
    "true",
    "false",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<Params>": [
    "int",
    "boolean",
    "const",
    "",
    "real",
    "Identifier",
    "struct",
    "string"
  ],
  "<Proc Decl>": ["procedure", "Identifier"],
  "<Assignment_vector>": ["=", ""],
  "<VariablesList>": [
    "Identifier",
    "boolean",
    "",
    "real",
    "string",
    "struct",
    "int"
  ],
  "<Assignment_matrix_aux1>": ["="],
  "<Body Item>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "return",
    "Identifier",
    "if",
    "DecLiteral",
    "false",
    "(",
    "HexLiteral",
    "FloatLiteral",
    "OctLiteral"
  ],
  "<Vector>": ["["],
  "<Body>": [
    "",
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "OctLiteral",
    "Identifier",
    "if",
    "DecLiteral",
    "FloatLiteral",
    "(",
    "HexLiteral",
    "false",
    "return"
  ],
  "<Decls>": ["Identifier", "struct", "function", "typedef", "procedure", ""],
  "<Const Decl>": ["const"],
  "<Expression Value Logical>": [
    "local.",
    "-",
    "true",
    "DecLiteral",
    "Identifier",
    "OctLiteral",
    "global.",
    "HexLiteral",
    "(",
    "StringLiteral",
    "false",
    "FloatLiteral"
  ],
  "<Logical>": ["||", "&&"],
  "<Decl>": ["Identifier", "struct", "function", "typedef", "procedure"],
  "<Assignment_matrix>": ["=", ""],
  "<Return Statement>": ["return"],
  "<Aux>": [";", ",", "=", "["],
  "<Add Exp>": ["+", "", "-"],
  "<Base>": ["Identifier", "boolean", "real", "string", "struct", "int"],
  "<Assign>": [
    "local.",
    "FloatLiteral",
    "true",
    "HexLiteral",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "false",
    "-"
  ],
  "<Exp>": [
    "local.",
    "-",
    "true",
    "false",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "HexLiteral",
    "FloatLiteral"
  ],
  "<Value_assigned_vector>": [
    "OctLiteral",
    "DecLiteral",
    "HexLiteral",
    "FloatLiteral",
    "StringLiteral",
    "true",
    "false"
  ],
  "<Program>": [
    "Identifier",
    "var",
    "typedef",
    "function",
    "const",
    "procedure",
    "struct"
  ],
  "<Conditional Expression>": [
    "local.",
    "!",
    "-",
    "true",
    "HexLiteral",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "false",
    "FloatLiteral"
  ],
  "<Delimiter Const>": [";", ","],
  "<Variable>": ["Identifier"],
  "<Formal Parameter List Read>": ["Identifier"],
  "<Var Decl>": ["var"],
  "<Assignment_vector_aux1>": ["="],
  "<Dimensao_matrix2>": [","],
  "<Start>": ["start"],
  "<Then Procedure>": [")"],
  "<Formal Parameter List>": [
    "local.",
    "",
    "FloatLiteral",
    "-",
    "HexLiteral",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<Body Procedure>": [
    "",
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "Identifier",
    "if",
    "DecLiteral",
    "OctLiteral",
    "(",
    "FloatLiteral",
    "false",
    "HexLiteral"
  ],
  "<Const>": ["Identifier"],
  "<Boolean Literal>": ["true", "false"],
  "<Conditional Operator>": ["||", "&&"],
  "<Print>": ["print"],
  "<While Procedure>": ["while"],
  "<While>": ["while"],
  "<Mult Exp>": ["", "*", "/"],
  "<Param>": [
    "int",
    "boolean",
    "const",
    "real",
    "string",
    "struct",
    "Identifier"
  ],
  "<Delimiter Var>": [";", ","],
  "<Expression Value>": [
    "-",
    "true",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "false",
    "(",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<Matrix>": ["["],
  "<Assignment_matrix_aux2>": ["="],
  "<Then>": [")"],
  "<If Procedure>": ["if"]
};
