const SourceFollow = <String, List<String>>{
  "<Logical Denied>": ["if", "while"],
  "<Index>": ["["],
  "<Function Call>": ["||", "&&", "*", "/"],
  "<Value_assigned_matrix>": ["=", ","],
  "<Number>": ["[", "=", "Identifier", ";", ",", "*", "/"],
  "<Logical Expression>": ["while", "if"],
  "<Global Decl>": ["Identifier", "struct", "function", "typedef", "procedure"],
  "<Else Procedure>": [],
  "<Term>": [
    "local.",
    "+",
    "FloatLiteral",
    "-",
    "HexLiteral",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<Type>": [
    "int",
    "real",
    "typedef",
    "string",
    "struct",
    "const",
    "function",
    "Identifier",
    "boolean"
  ],
  "<Typedef Decl>": [
    "Identifier",
    "struct",
    "function",
    "typedef",
    "procedure"
  ],
  "<Relational>": ["if", "&&", "||", "while"],
  "<Function Declaration>": [
    "Identifier",
    "struct",
    "function",
    "typedef",
    "procedure"
  ],
  "<Body Item Procedure>": [
    "-",
    "while",
    "OctLiteral",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "Identifier",
    "if",
    "DecLiteral",
    "HexLiteral",
    "(",
    "false",
    "FloatLiteral",
    "var"
  ],
  "<Relational Expression>": ["&&", "if", "||", "while"],
  "<If>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "OctLiteral",
    "Identifier",
    "if",
    "DecLiteral",
    "FloatLiteral",
    "(",
    "HexLiteral",
    "false",
    "return"
  ],
  "<Else>": [],
  "<ConstList>": ["const"],
  "<Struct Decl>": ["Identifier", "struct", "function", "typedef", "procedure"],
  "<Assignment_vector_aux2>": [
    "[",
    "local.",
    "HexLiteral",
    "FloatLiteral",
    ";",
    ",",
    "-",
    "=",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<Extends>": ["string", "boolean", "real", "int", "struct", "Identifier"],
  "<PrefixGlobalLocal>": [
    "true",
    "-",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "false",
    "(",
    "StringLiteral",
    "HexLiteral",
    "FloatLiteral"
  ],
  "<Read>": [
    "-",
    "while",
    "OctLiteral",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "return",
    "Identifier",
    "if",
    "DecLiteral",
    "var",
    "(",
    "FloatLiteral",
    "HexLiteral",
    "false"
  ],
  "<Value>": ["Identifier", "=", ",", "[", ";"],
  "<Params>": ["Identifier", "procedure", "function"],
  "<Proc Decl>": ["Identifier", "struct", "function", "typedef", "procedure"],
  "<Assignment_vector>": [
    "[",
    "local.",
    "-",
    "false",
    "Identifier",
    ",",
    "true",
    "DecLiteral",
    ";",
    "OctLiteral",
    "=",
    "global.",
    "(",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<VariablesList>": [
    "Identifier",
    "struct",
    "int",
    "real",
    "string",
    "var",
    "boolean"
  ],
  "<Assignment_matrix_aux1>": [
    "[",
    "local.",
    "HexLiteral",
    "FloatLiteral",
    ";",
    ",",
    "-",
    "=",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<Body Item>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "return",
    "Identifier",
    "if",
    "DecLiteral",
    "false",
    "(",
    "HexLiteral",
    "FloatLiteral",
    "OctLiteral"
  ],
  "<Vector>": [
    "local.",
    "-",
    "false",
    "true",
    "=",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<Body>": ["function", "else", ")", "while"],
  "<Decls>": [
    "Identifier",
    "var",
    "struct",
    "\$",
    "function",
    "typedef",
    "procedure",
    "const"
  ],
  "<Const Decl>": [
    "Identifier",
    "struct",
    "function",
    "typedef",
    "procedure",
    "var"
  ],
  "<Expression Value Logical>": ["||", "&&"],
  "<Logical>": [],
  "<Decl>": ["Identifier", "struct", "function", "typedef", "procedure"],
  "<Assignment_matrix>": [
    "[",
    "local.",
    "-",
    "false",
    "Identifier",
    ",",
    "true",
    "DecLiteral",
    ";",
    "OctLiteral",
    "=",
    "global.",
    "(",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<Return Statement>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "OctLiteral",
    "Identifier",
    "if",
    "DecLiteral",
    "FloatLiteral",
    "(",
    "HexLiteral",
    "false",
    "return"
  ],
  "<Aux>": ["string", "var", "Identifier", "real", "struct", "int", "boolean"],
  "<Add Exp>": [
    "||",
    ",",
    "==",
    "<=",
    "OctLiteral",
    "global.",
    "if",
    "StringLiteral",
    "&&",
    "while",
    "!=",
    "local.",
    "false",
    "-",
    ">=",
    "print",
    "procedure",
    "Identifier",
    ";",
    "<",
    "DecLiteral",
    ">",
    "(",
    "HexLiteral",
    "FloatLiteral",
    "true"
  ],
  "<Base>": ["typedef"],
  "<Assign>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "OctLiteral",
    "Identifier",
    "if",
    "DecLiteral",
    "FloatLiteral",
    "(",
    "HexLiteral",
    "false",
    "return"
  ],
  "<Delimiter Var>": [],
  "<Value_assigned_vector>": ["="],
  "<While>": [
    "-",
    "while",
    "var",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "OctLiteral",
    "Identifier",
    "if",
    "DecLiteral",
    "FloatLiteral",
    "(",
    "HexLiteral",
    "false",
    "return"
  ],
  "<Conditional Expression>": ["if", "while"],
  "<Param>": ["Identifier", ",", "procedure", "function"],
  "<Assignment_matrix_aux2>": [
    "[",
    "local.",
    "HexLiteral",
    "FloatLiteral",
    ";",
    ",",
    "-",
    "=",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<Formal Parameter List Read>": ["read", ","],
  "<Dimensao_matrix2>": [
    "[",
    "local.",
    "true",
    "false",
    "Identifier",
    ",",
    "-",
    "DecLiteral",
    ";",
    "OctLiteral",
    "=",
    "global.",
    "(",
    "StringLiteral",
    "HexLiteral",
    "FloatLiteral"
  ],
  "<Assignment_vector_aux1>": [
    "[",
    "local.",
    "HexLiteral",
    "FloatLiteral",
    ";",
    ",",
    "-",
    "=",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "false",
    "true"
  ],
  "<Var Decl>": [
    "-",
    "while",
    "OctLiteral",
    "global.",
    "const",
    "return",
    "var",
    "FloatLiteral",
    "local.",
    "false",
    "(",
    "read",
    "typedef",
    "procedure",
    "struct",
    "Identifier",
    "if",
    "DecLiteral",
    "true",
    "function",
    "print",
    "HexLiteral",
    "StringLiteral"
  ],
  "<Variable>": [
    "string",
    "boolean",
    "var",
    "real",
    "int",
    "struct",
    "Identifier"
  ],
  "<Conditional Operator>": [
    "local.",
    "!",
    "FloatLiteral",
    "-",
    "false",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "HexLiteral",
    "true"
  ],
  "<Delimiter Const>": [
    "int",
    "boolean",
    "Identifier",
    "real",
    "const",
    "struct",
    "string"
  ],
  "<Body Procedure>": [
    "Identifier",
    "while",
    "start",
    "else",
    "procedure",
    ")"
  ],
  "<Const>": [
    "string",
    "boolean",
    "int",
    "real",
    "const",
    "struct",
    "Identifier"
  ],
  "<Boolean Literal>": [
    "[",
    "||",
    ",",
    "while",
    "Identifier",
    "&&",
    "=",
    "if",
    ";",
    "*",
    "/"
  ],
  "<Start>": ["\$"],
  "<Print>": [
    "-",
    "while",
    "OctLiteral",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "return",
    "Identifier",
    "if",
    "DecLiteral",
    "var",
    "(",
    "FloatLiteral",
    "HexLiteral",
    "false"
  ],
  "<While Procedure>": [
    "-",
    "while",
    "OctLiteral",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "Identifier",
    "if",
    "DecLiteral",
    "var",
    "(",
    "FloatLiteral",
    "HexLiteral",
    "false"
  ],
  "<Formal Parameter List>": ["Identifier", "print", "procedure"],
  "<Expression Value>": ["*", "/"],
  "<Then Procedure>": [],
  "<Exp>": [
    "||",
    ",",
    "==",
    "<=",
    "OctLiteral",
    "global.",
    "while",
    "StringLiteral",
    "&&",
    "if",
    ";",
    "local.",
    "procedure",
    "FloatLiteral",
    "HexLiteral",
    "print",
    "true",
    "(",
    "Identifier",
    "<",
    "DecLiteral",
    ">",
    ">=",
    "-",
    "false",
    "!="
  ],
  "<Mult Exp>": [
    "local.",
    "+",
    "true",
    "-",
    "false",
    "Identifier",
    "OctLiteral",
    "global.",
    "DecLiteral",
    "(",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<Matrix>": [
    "local.",
    "-",
    "false",
    "true",
    "=",
    "Identifier",
    "OctLiteral",
    "DecLiteral",
    "global.",
    "(",
    "StringLiteral",
    "FloatLiteral",
    "HexLiteral"
  ],
  "<If Procedure>": [
    "-",
    "while",
    "OctLiteral",
    "global.",
    "StringLiteral",
    "local.",
    "read",
    "print",
    "true",
    "Identifier",
    "if",
    "DecLiteral",
    "var",
    "(",
    "FloatLiteral",
    "HexLiteral",
    "false"
  ],
  "<Program>": ["\$"],
  "<Then>": []
};
